### ISSUE TITLE
Recaptcha appears empty

### ISSUE THREAD

**Issue by manupeco** [arjayosma/expo-firebase-phone-authentication#5]
**Step to reproduce**

- Clone the repo
- Run yarn install
- Put my firebase config
- Run on Android emulator
- Enter phone number and push Send Verification

Result:
Recpatcha modal appears completely empty

Expected: 
The Modal should contain the I'm not a robot checkbox

**Comment by arjayosma** [comment]
Hi @manupeco, as mentioned in our Twitter DM, can you send a copy/screenshot of your configuration?
A copy of the following files would suffice:

- firebase.js
- app.json

Please hide sensitive details.
Would love to check these out.

**Comment by arjayosma** [comment]
Closing as this is fixed now.

@manupeco confirmed to have worked after trying a different firebase configuration and reverted back to the original configuration he used.

Thanks!
